<a href="https://colab.research.google.com/github/sohaildua/ComputerVision/blob/main/NumpyWithImages.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.zeros(shape =(10,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [22]:
np.random.seed(101)
arr =np.random.randint(0,100,10)

In [23]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [24]:
arr2 = np.random.randint(0,100,10)

In [25]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [26]:
arr.max()

95

In [27]:
arr.argmax()

0

In [28]:
arr.min()

9

In [32]:
arr.shape

(10,)